id: A2F482285
base_file: f8263.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:41:39.446674
  last_modified_at: 2022-05-30 20:41:39.446678
