id: A2F482285
base_file: fBA3B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:41:39.447662
  last_modified_at: 2022-05-30 20:41:39.447664
